/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatrizRouteImport } from './routes/matriz'
import { Route as SistemasRouteImport } from './routes/sistemas'
import { Route as ApiEvolutionRouteImport } from './routes/api/evolution'
import { Route as ApiIsabellaRouteImport } from './routes/api/isabella'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrizRoute = MatrizRouteImport.update({
  id: '/matriz',
  path: '/matriz',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemasRoute = SistemasRouteImport.update({
  id: '/sistemas',
  path: '/sistemas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvolutionRoute = ApiEvolutionRouteImport.update({
  id: '/api/evolution',
  path: '/api/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIsabellaRoute = ApiIsabellaRouteImport.update({
  id: '/api/isabella',
  path: '/api/isabella',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/matriz': typeof MatrizRoute
  '/sistemas': typeof SistemasRoute
  '/api/evolution': typeof ApiEvolutionRoute
  '/api/isabella': typeof ApiIsabellaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matriz': typeof MatrizRoute
  '/sistemas': typeof SistemasRoute
  '/api/evolution': typeof ApiEvolutionRoute
  '/api/isabella': typeof ApiIsabellaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/matriz': typeof MatrizRoute
  '/sistemas': typeof SistemasRoute
  '/api/evolution': typeof ApiEvolutionRoute
  '/api/isabella': typeof ApiIsabellaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/matriz' | '/sistemas' | '/api/evolution' | '/api/isabella'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/matriz' | '/sistemas' | '/api/evolution' | '/api/isabella'
  id:
    | '__root__'
    | '/'
    | '/matriz'
    | '/sistemas'
    | '/api/evolution'
    | '/api/isabella'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatrizRoute: typeof MatrizRoute
  SistemasRoute: typeof SistemasRoute
  ApiEvolutionRoute: typeof ApiEvolutionRoute
  ApiIsabellaRoute: typeof ApiIsabellaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matriz': {
      id: '/matriz'
      path: '/matriz'
      fullPath: '/matriz'
      preLoaderRoute: typeof MatrizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas': {
      id: '/sistemas'
      path: '/sistemas'
      fullPath: '/sistemas'
      preLoaderRoute: typeof SistemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evolution': {
      id: '/api/evolution'
      path: '/api/evolution'
      fullPath: '/api/evolution'
      preLoaderRoute: typeof ApiEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/isabella': {
      id: '/api/isabella'
      path: '/api/isabella'
      fullPath: '/api/isabella'
      preLoaderRoute: typeof ApiIsabellaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatrizRoute: MatrizRoute,
  SistemasRoute: SistemasRoute,
  ApiEvolutionRoute: ApiEvolutionRoute,
  ApiIsabellaRoute: ApiIsabellaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
